// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for SendMessageFunction
 */
export interface SendMessageFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/send-message.
 */
export class SendMessageFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: SendMessageFunctionProps) {
    super(scope, id, {
      description: 'src/send-message.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs22.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../assets/send-message.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}